//! Static tool registry for agent discovery.
//!
//! All CLI tools are registered here as compile-time constants.
//! `cho tools --json` serves this catalog to agents for self-discovery.

/// Metadata for a single CLI tool.
pub struct ToolMeta {
    /// Dotted tool name (e.g., "invoices.list").
    pub name: &'static str,
    /// Full CLI command (e.g., "cho invoices list").
    pub command: &'static str,
    /// Category grouping.
    pub category: &'static str,
    /// Human-readable description.
    pub description: &'static str,
    /// Parameter definitions.
    pub parameters: &'static [ParamMeta],
    /// Key output fields (for agent field selection).
    pub output_fields: &'static [&'static str],
    /// Whether the operation is safe to retry.
    pub idempotent: bool,
    /// Rate limit group, if applicable.
    pub rate_limit: Option<&'static str>,
    /// Example invocation.
    pub example: &'static str,
}

/// Metadata for a tool parameter.
#[derive(Copy, Clone)]
pub struct ParamMeta {
    /// Parameter name (e.g., "--where" or "<id>").
    pub name: &'static str,
    /// Type hint (e.g., "string", "uuid", "boolean", "path", "date").
    pub param_type: &'static str,
    /// Whether the parameter is required.
    pub required: bool,
    /// Description.
    pub description: &'static str,
}

/// Metadata for a global flag.
pub struct GlobalFlagMeta {
    /// Flag name (e.g., "--format").
    pub name: &'static str,
    /// Description.
    pub description: &'static str,
    /// Default value.
    pub default: &'static str,
}

// --- Global flags ---

/// All global flags available on every command.
pub static GLOBAL_FLAGS: &[GlobalFlagMeta] = &[
    GlobalFlagMeta {
        name: "--json",
        description: "Output as JSON with envelope",
        default: "false",
    },
    GlobalFlagMeta {
        name: "--format",
        description: "Output format: json, table, csv",
        default: "auto (json if piped, table if TTY)",
    },
    GlobalFlagMeta {
        name: "--raw",
        description: "Preserve PascalCase keys (skip snake_case)",
        default: "false",
    },
    GlobalFlagMeta {
        name: "--precise",
        description: "Emit money as strings instead of numbers",
        default: "false",
    },
    GlobalFlagMeta {
        name: "--tenant",
        description: "Override default tenant ID",
        default: "from config",
    },
    GlobalFlagMeta {
        name: "--limit",
        description: "Maximum items for list commands",
        default: "100",
    },
    GlobalFlagMeta {
        name: "--all",
        description: "Fetch all pages, no limit",
        default: "false",
    },
    GlobalFlagMeta {
        name: "--verbose",
        description: "Enable tracing output",
        default: "false",
    },
    GlobalFlagMeta {
        name: "--quiet",
        description: "Suppress non-essential output",
        default: "false",
    },
    GlobalFlagMeta {
        name: "--no-color",
        description: "Disable terminal colors",
        default: "false",
    },
];

// --- Common parameter sets ---

static WHERE_PARAM: ParamMeta = ParamMeta {
    name: "--where",
    param_type: "string",
    required: false,
    description: "OData filter expression",
};

static ORDER_PARAM: ParamMeta = ParamMeta {
    name: "--order",
    param_type: "string",
    required: false,
    description: "Sort expression (e.g. \"Date DESC\")",
};

static FILE_PARAM: ParamMeta = ParamMeta {
    name: "--file",
    param_type: "path",
    required: true,
    description: "Path to JSON file with request payload",
};

static IDEMPOTENCY_PARAM: ParamMeta = ParamMeta {
    name: "--idempotency-key",
    param_type: "string",
    required: false,
    description: "Idempotency key for safe retries",
};

static UUID_PARAM: ParamMeta = ParamMeta {
    name: "<id>",
    param_type: "uuid",
    required: true,
    description: "Resource UUID",
};

// --- Tool catalog ---

/// Complete catalog of all CLI tools.
pub static TOOLS: &[ToolMeta] = &[
    // --- Init ---
    ToolMeta {
        name: "init.setup",
        command: "cho init",
        category: "init",
        description: "Interactive first-time setup: authenticate and select a tenant",
        parameters: &[
            ParamMeta {
                name: "--client-id",
                param_type: "string",
                required: false,
                description: "Xero OAuth 2.0 client ID (or set CHO_CLIENT_ID env var)",
            },
            ParamMeta {
                name: "--port",
                param_type: "number",
                required: false,
                description: "Port for localhost callback server (0 = auto)",
            },
        ],
        output_fields: &["config", "client_id", "tenant_id"],
        idempotent: true,
        rate_limit: None,
        example: "cho init",
    },
    // --- Auth ---
    ToolMeta {
        name: "auth.login",
        command: "cho auth login",
        category: "auth",
        description: "Authenticate via OAuth 2.0 PKCE (opens browser)",
        parameters: &[
            ParamMeta {
                name: "--client-credentials",
                param_type: "boolean",
                required: false,
                description: "Use client credentials instead of PKCE",
            },
            ParamMeta {
                name: "--port",
                param_type: "number",
                required: false,
                description: "Port for localhost callback (0 = auto)",
            },
        ],
        output_fields: &["authenticated"],
        idempotent: true,
        rate_limit: None,
        example: "cho auth login",
    },
    ToolMeta {
        name: "auth.status",
        command: "cho auth status",
        category: "auth",
        description: "Show current authentication status",
        parameters: &[],
        output_fields: &["authenticated", "tenant_id"],
        idempotent: true,
        rate_limit: None,
        example: "cho auth status --json",
    },
    ToolMeta {
        name: "auth.refresh",
        command: "cho auth refresh",
        category: "auth",
        description: "Force token refresh",
        parameters: &[],
        output_fields: &["refreshed"],
        idempotent: false,
        rate_limit: None,
        example: "cho auth refresh --json",
    },
    ToolMeta {
        name: "auth.tenants",
        command: "cho auth tenants",
        category: "auth",
        description: "List connected organisations",
        parameters: &[],
        output_fields: &["tenant_id", "tenant_name", "tenant_type"],
        idempotent: true,
        rate_limit: Some("identity"),
        example: "cho auth tenants --json",
    },
    // --- Invoices ---
    ToolMeta {
        name: "invoices.list",
        command: "cho invoices list",
        category: "invoices",
        description: "List invoices with optional filtering",
        parameters: &[
            WHERE_PARAM,
            ORDER_PARAM,
            ParamMeta {
                name: "--from",
                param_type: "date",
                required: false,
                description: "Filter from date (YYYY-MM-DD)",
            },
            ParamMeta {
                name: "--to",
                param_type: "date",
                required: false,
                description: "Filter to date (YYYY-MM-DD)",
            },
            ParamMeta {
                name: "--summary",
                param_type: "boolean",
                required: false,
                description: "Return summary only (fewer fields)",
            },
        ],
        output_fields: &[
            "invoice_id",
            "invoice_number",
            "type",
            "status",
            "total",
            "date",
            "due_date",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho invoices list --where 'Status==\"AUTHORISED\"' --json",
    },
    ToolMeta {
        name: "invoices.get",
        command: "cho invoices get",
        category: "invoices",
        description: "Get a single invoice by ID or number",
        parameters: &[ParamMeta {
            name: "<id-or-number>",
            param_type: "string",
            required: true,
            description: "Invoice UUID or invoice number",
        }],
        output_fields: &[
            "invoice_id",
            "invoice_number",
            "type",
            "status",
            "total",
            "line_items",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho invoices get INV-001 --json",
    },
    ToolMeta {
        name: "invoices.create",
        command: "cho invoices create",
        category: "invoices",
        description: "Create a new invoice from JSON file",
        parameters: &[FILE_PARAM, IDEMPOTENCY_PARAM],
        output_fields: &["invoice_id", "invoice_number", "status"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho invoices create --file invoice.json --json",
    },
    ToolMeta {
        name: "invoices.update",
        command: "cho invoices update",
        category: "invoices",
        description: "Update an existing invoice",
        parameters: &[UUID_PARAM, FILE_PARAM, IDEMPOTENCY_PARAM],
        output_fields: &["invoice_id", "status"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho invoices update <UUID> --file update.json --json",
    },
    // --- Contacts ---
    ToolMeta {
        name: "contacts.list",
        command: "cho contacts list",
        category: "contacts",
        description: "List contacts with optional filtering",
        parameters: &[WHERE_PARAM],
        output_fields: &["contact_id", "name", "email_address", "contact_status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho contacts list --json",
    },
    ToolMeta {
        name: "contacts.get",
        command: "cho contacts get",
        category: "contacts",
        description: "Get a single contact by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["contact_id", "name", "email_address", "phones", "addresses"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho contacts get <UUID> --json",
    },
    ToolMeta {
        name: "contacts.search",
        command: "cho contacts search",
        category: "contacts",
        description: "Search contacts by name, email, etc.",
        parameters: &[ParamMeta {
            name: "<term>",
            param_type: "string",
            required: true,
            description: "Search term",
        }],
        output_fields: &["contact_id", "name", "email_address"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho contacts search \"Acme\" --json",
    },
    ToolMeta {
        name: "contacts.create",
        command: "cho contacts create",
        category: "contacts",
        description: "Create a new contact from JSON file",
        parameters: &[FILE_PARAM, IDEMPOTENCY_PARAM],
        output_fields: &["contact_id", "name"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho contacts create --file contact.json --json",
    },
    ToolMeta {
        name: "contacts.update",
        command: "cho contacts update",
        category: "contacts",
        description: "Update an existing contact",
        parameters: &[UUID_PARAM, FILE_PARAM, IDEMPOTENCY_PARAM],
        output_fields: &["contact_id", "name"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho contacts update <UUID> --file update.json --json",
    },
    // --- Payments ---
    ToolMeta {
        name: "payments.list",
        command: "cho payments list",
        category: "payments",
        description: "List payments with optional filtering",
        parameters: &[WHERE_PARAM],
        output_fields: &["payment_id", "date", "amount", "status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho payments list --json",
    },
    ToolMeta {
        name: "payments.get",
        command: "cho payments get",
        category: "payments",
        description: "Get a single payment by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["payment_id", "date", "amount", "invoice", "account"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho payments get <UUID> --json",
    },
    ToolMeta {
        name: "payments.create",
        command: "cho payments create",
        category: "payments",
        description: "Create a new payment",
        parameters: &[FILE_PARAM, IDEMPOTENCY_PARAM],
        output_fields: &["payment_id", "status"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho payments create --file payment.json --json",
    },
    ToolMeta {
        name: "payments.delete",
        command: "cho payments delete",
        category: "payments",
        description: "Delete a payment by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["payment_id", "status"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho payments delete <UUID> --json",
    },
    // --- Transactions ---
    ToolMeta {
        name: "transactions.list",
        command: "cho transactions list",
        category: "transactions",
        description: "List bank transactions with optional filtering",
        parameters: &[
            WHERE_PARAM,
            ORDER_PARAM,
            ParamMeta {
                name: "--from",
                param_type: "date",
                required: false,
                description: "Filter from date (YYYY-MM-DD)",
            },
            ParamMeta {
                name: "--to",
                param_type: "date",
                required: false,
                description: "Filter to date (YYYY-MM-DD)",
            },
        ],
        output_fields: &["bank_transaction_id", "type", "date", "total", "status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho transactions list --from 2024-01-01 --json",
    },
    ToolMeta {
        name: "transactions.get",
        command: "cho transactions get",
        category: "transactions",
        description: "Get a single bank transaction by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["bank_transaction_id", "type", "date", "total", "line_items"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho transactions get <UUID> --json",
    },
    ToolMeta {
        name: "transactions.create",
        command: "cho transactions create",
        category: "transactions",
        description: "Create a bank transaction",
        parameters: &[FILE_PARAM, IDEMPOTENCY_PARAM],
        output_fields: &["bank_transaction_id", "status"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho transactions create --file txn.json --json",
    },
    ToolMeta {
        name: "transactions.update",
        command: "cho transactions update",
        category: "transactions",
        description: "Update a bank transaction",
        parameters: &[UUID_PARAM, FILE_PARAM, IDEMPOTENCY_PARAM],
        output_fields: &["bank_transaction_id", "status"],
        idempotent: false,
        rate_limit: Some("accounting"),
        example: "cho transactions update <UUID> --file update.json --json",
    },
    // --- Accounts ---
    ToolMeta {
        name: "accounts.list",
        command: "cho accounts list",
        category: "accounts",
        description: "List chart of accounts",
        parameters: &[WHERE_PARAM],
        output_fields: &["account_id", "code", "name", "type", "class", "status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho accounts list --where 'Type==\"BANK\"' --json",
    },
    // --- Reports ---
    ToolMeta {
        name: "reports.balance-sheet",
        command: "cho reports balance-sheet",
        category: "reports",
        description: "Balance Sheet report",
        parameters: &[
            ParamMeta {
                name: "--date",
                param_type: "date",
                required: false,
                description: "Report date (YYYY-MM-DD)",
            },
            ParamMeta {
                name: "--periods",
                param_type: "number",
                required: false,
                description: "Number of comparison periods",
            },
            ParamMeta {
                name: "--timeframe",
                param_type: "string",
                required: false,
                description: "MONTH, QUARTER, or YEAR",
            },
        ],
        output_fields: &["report_name", "rows"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho reports balance-sheet --date 2024-12-31 --json",
    },
    ToolMeta {
        name: "reports.pnl",
        command: "cho reports pnl",
        category: "reports",
        description: "Profit and Loss report",
        parameters: &[
            ParamMeta {
                name: "--from",
                param_type: "date",
                required: false,
                description: "From date (YYYY-MM-DD)",
            },
            ParamMeta {
                name: "--to",
                param_type: "date",
                required: false,
                description: "To date (YYYY-MM-DD)",
            },
            ParamMeta {
                name: "--periods",
                param_type: "number",
                required: false,
                description: "Number of comparison periods",
            },
            ParamMeta {
                name: "--timeframe",
                param_type: "string",
                required: false,
                description: "MONTH, QUARTER, or YEAR",
            },
        ],
        output_fields: &["report_name", "rows"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho reports pnl --from 2024-01-01 --to 2024-12-31 --json",
    },
    ToolMeta {
        name: "reports.trial-balance",
        command: "cho reports trial-balance",
        category: "reports",
        description: "Trial Balance report",
        parameters: &[ParamMeta {
            name: "--date",
            param_type: "date",
            required: false,
            description: "Report date (YYYY-MM-DD)",
        }],
        output_fields: &["report_name", "rows"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho reports trial-balance --json",
    },
    ToolMeta {
        name: "reports.aged-payables",
        command: "cho reports aged-payables",
        category: "reports",
        description: "Aged Payables report",
        parameters: &[
            ParamMeta {
                name: "--contact",
                param_type: "uuid",
                required: false,
                description: "Filter by contact ID",
            },
            ParamMeta {
                name: "--date",
                param_type: "date",
                required: false,
                description: "Report date (YYYY-MM-DD)",
            },
        ],
        output_fields: &["report_name", "rows"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho reports aged-payables --json",
    },
    ToolMeta {
        name: "reports.aged-receivables",
        command: "cho reports aged-receivables",
        category: "reports",
        description: "Aged Receivables report",
        parameters: &[
            ParamMeta {
                name: "--contact",
                param_type: "uuid",
                required: false,
                description: "Filter by contact ID",
            },
            ParamMeta {
                name: "--date",
                param_type: "date",
                required: false,
                description: "Report date (YYYY-MM-DD)",
            },
        ],
        output_fields: &["report_name", "rows"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho reports aged-receivables --json",
    },
    // --- Config ---
    ToolMeta {
        name: "config.show",
        command: "cho config show",
        category: "config",
        description: "Show current configuration",
        parameters: &[],
        output_fields: &[],
        idempotent: true,
        rate_limit: None,
        example: "cho config show --json",
    },
    ToolMeta {
        name: "config.set",
        command: "cho config set",
        category: "config",
        description: "Set a configuration value",
        parameters: &[
            ParamMeta {
                name: "<key>",
                param_type: "string",
                required: true,
                description: "Config key (e.g. auth.tenant_id)",
            },
            ParamMeta {
                name: "<value>",
                param_type: "string",
                required: true,
                description: "Value to set",
            },
        ],
        output_fields: &["key", "value"],
        idempotent: true,
        rate_limit: None,
        example: "cho config set auth.tenant_id <UUID> --json",
    },
    // --- Credit Notes ---
    ToolMeta {
        name: "credit-notes.list",
        command: "cho credit-notes list",
        category: "credit-notes",
        description: "List credit notes",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &[
            "credit_note_id",
            "credit_note_number",
            "type",
            "status",
            "total",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho credit-notes list --json",
    },
    ToolMeta {
        name: "credit-notes.get",
        command: "cho credit-notes get",
        category: "credit-notes",
        description: "Get a single credit note by ID",
        parameters: &[UUID_PARAM],
        output_fields: &[
            "credit_note_id",
            "credit_note_number",
            "type",
            "status",
            "total",
            "line_items",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho credit-notes get <UUID> --json",
    },
    // --- Quotes ---
    ToolMeta {
        name: "quotes.list",
        command: "cho quotes list",
        category: "quotes",
        description: "List quotes",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &["quote_id", "quote_number", "status", "total", "date"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho quotes list --json",
    },
    ToolMeta {
        name: "quotes.get",
        command: "cho quotes get",
        category: "quotes",
        description: "Get a single quote by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["quote_id", "quote_number", "status", "total", "line_items"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho quotes get <UUID> --json",
    },
    // --- Purchase Orders ---
    ToolMeta {
        name: "purchase-orders.list",
        command: "cho purchase-orders list",
        category: "purchase-orders",
        description: "List purchase orders",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &[
            "purchase_order_id",
            "purchase_order_number",
            "status",
            "total",
            "date",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho purchase-orders list --json",
    },
    ToolMeta {
        name: "purchase-orders.get",
        command: "cho purchase-orders get",
        category: "purchase-orders",
        description: "Get a single purchase order by ID",
        parameters: &[UUID_PARAM],
        output_fields: &[
            "purchase_order_id",
            "purchase_order_number",
            "status",
            "total",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho purchase-orders get <UUID> --json",
    },
    // --- Items ---
    ToolMeta {
        name: "items.list",
        command: "cho items list",
        category: "items",
        description: "List items",
        parameters: &[WHERE_PARAM],
        output_fields: &["item_id", "code", "name", "is_sold", "is_purchased"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho items list --json",
    },
    ToolMeta {
        name: "items.get",
        command: "cho items get",
        category: "items",
        description: "Get a single item by ID",
        parameters: &[UUID_PARAM],
        output_fields: &[
            "item_id",
            "code",
            "name",
            "description",
            "purchase_details",
            "sales_details",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho items get <UUID> --json",
    },
    // --- Tax Rates ---
    ToolMeta {
        name: "tax-rates.list",
        command: "cho tax-rates list",
        category: "tax-rates",
        description: "List tax rates",
        parameters: &[WHERE_PARAM],
        output_fields: &["name", "tax_type", "effective_rate", "status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho tax-rates list --json",
    },
    // --- Currencies ---
    ToolMeta {
        name: "currencies.list",
        command: "cho currencies list",
        category: "currencies",
        description: "List currencies",
        parameters: &[WHERE_PARAM],
        output_fields: &["code", "description"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho currencies list --json",
    },
    // --- Tracking Categories ---
    ToolMeta {
        name: "tracking-categories.list",
        command: "cho tracking-categories list",
        category: "tracking-categories",
        description: "List tracking categories",
        parameters: &[WHERE_PARAM],
        output_fields: &["tracking_category_id", "name", "status", "options"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho tracking-categories list --json",
    },
    ToolMeta {
        name: "tracking-categories.get",
        command: "cho tracking-categories get",
        category: "tracking-categories",
        description: "Get a single tracking category by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["tracking_category_id", "name", "status", "options"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho tracking-categories get <UUID> --json",
    },
    // --- Organisation ---
    ToolMeta {
        name: "organisation.get",
        command: "cho organisation get",
        category: "organisation",
        description: "Get organisation details",
        parameters: &[],
        output_fields: &[
            "organisation_id",
            "name",
            "legal_name",
            "base_currency",
            "country_code",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho organisation get --json",
    },
    // --- Manual Journals ---
    ToolMeta {
        name: "manual-journals.list",
        command: "cho manual-journals list",
        category: "manual-journals",
        description: "List manual journals",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &["manual_journal_id", "narration", "date", "status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho manual-journals list --json",
    },
    ToolMeta {
        name: "manual-journals.get",
        command: "cho manual-journals get",
        category: "manual-journals",
        description: "Get a single manual journal by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["manual_journal_id", "narration", "date", "journal_lines"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho manual-journals get <UUID> --json",
    },
    // --- Prepayments ---
    ToolMeta {
        name: "prepayments.list",
        command: "cho prepayments list",
        category: "prepayments",
        description: "List prepayments",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &["prepayment_id", "type", "date", "total", "status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho prepayments list --json",
    },
    ToolMeta {
        name: "prepayments.get",
        command: "cho prepayments get",
        category: "prepayments",
        description: "Get a single prepayment by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["prepayment_id", "type", "date", "total"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho prepayments get <UUID> --json",
    },
    // --- Overpayments ---
    ToolMeta {
        name: "overpayments.list",
        command: "cho overpayments list",
        category: "overpayments",
        description: "List overpayments",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &["overpayment_id", "type", "date", "total", "status"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho overpayments list --json",
    },
    ToolMeta {
        name: "overpayments.get",
        command: "cho overpayments get",
        category: "overpayments",
        description: "Get a single overpayment by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["overpayment_id", "type", "date", "total"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho overpayments get <UUID> --json",
    },
    // --- Linked Transactions ---
    ToolMeta {
        name: "linked-transactions.list",
        command: "cho linked-transactions list",
        category: "linked-transactions",
        description: "List linked transactions",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &[
            "linked_transaction_id",
            "source_transaction_id",
            "contact_id",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho linked-transactions list --json",
    },
    ToolMeta {
        name: "linked-transactions.get",
        command: "cho linked-transactions get",
        category: "linked-transactions",
        description: "Get a single linked transaction by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["linked_transaction_id", "source_transaction_id"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho linked-transactions get <UUID> --json",
    },
    // --- Budgets ---
    ToolMeta {
        name: "budgets.list",
        command: "cho budgets list",
        category: "budgets",
        description: "List budgets",
        parameters: &[WHERE_PARAM],
        output_fields: &["budget_id", "description", "type"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho budgets list --json",
    },
    ToolMeta {
        name: "budgets.get",
        command: "cho budgets get",
        category: "budgets",
        description: "Get a single budget by ID",
        parameters: &[UUID_PARAM],
        output_fields: &["budget_id", "description", "type", "tracking"],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho budgets get <UUID> --json",
    },
    // --- Repeating Invoices ---
    ToolMeta {
        name: "repeating-invoices.list",
        command: "cho repeating-invoices list",
        category: "repeating-invoices",
        description: "List repeating invoices",
        parameters: &[WHERE_PARAM, ORDER_PARAM],
        output_fields: &[
            "repeating_invoice_id",
            "type",
            "status",
            "total",
            "schedule",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho repeating-invoices list --json",
    },
    ToolMeta {
        name: "repeating-invoices.get",
        command: "cho repeating-invoices get",
        category: "repeating-invoices",
        description: "Get a single repeating invoice by ID",
        parameters: &[UUID_PARAM],
        output_fields: &[
            "repeating_invoice_id",
            "type",
            "status",
            "total",
            "schedule",
        ],
        idempotent: true,
        rate_limit: Some("accounting"),
        example: "cho repeating-invoices get <UUID> --json",
    },
];
